name: Build libunwind for Android

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        HOST_ARCH: [armv7a-linux-androideabi, aarch64-linux-android]
        TARGET_ARCH: [arm-unknown-linux-androideabi, aarch64-unknown-linux-android]
        ANDROID_API: [21, 22, 23, 24, 26, 27, 28, 29]

    steps:
    - name: Build 
      run: |
        echo "Creating directory on temporary disk (14GB)"
        export ANDROID_HOME="/mnt/android-sdk"
        sudo mkdir "$ANDROID_HOME"
        sudo chown $(id -u):$(id -g) "$ANDROID_HOME"

        echo "Installing dependencies"
        sudo apt-get update -qq
        sudo apt-get install default-jdk -qq
        sudo apt-get install build-essential subversion swig python2.7-dev libedit-dev libncurses5-dev -qq # LLVM

        echo "Installing Android SDK"
        # Get the latest SDK at https://developer.android.com/studio
        curl -o sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip
        unzip -qq sdk.zip -d "$ANDROID_HOME"
        rm sdk.zip

        echo "Installing Android NDK"
        yes | "$ANDROID_HOME"/tools/bin/sdkmanager "cmake;3.10.2.4988404" "ndk;20.1.5948944" > /dev/null
        export NDK="$ANDROID_HOME"/ndk/20.1.5948944

        echo "Cloning libunwind"
        HONGGFUZZ_SRC="$(pwd)/src/honggfuzz"
        git clone --single-branch --branch patch/ci --depth 1 https://github.com/ilian/honggfuzz.git "$HONGGFUZZ_SRC"

        echo "Building libunwind"
        pushd "$HONGGFUZZ_SRC"
        export ANDROID_API=android-${{matrix.ANDROID_API}}
        ./third_party/android/scripts/compile-libunwind.sh third_party/android/libunwind/ ${{matrix.HOST_ARCH}} --target ${{matrix.TARGET_ARCH}}
        popd
        
        echo "Resulting build tree:"
        find "$HONGGFUZZ_SRC"/third_party/android/libunwind/src/.libs/
        
        echo "Packing artifact"
        mkdir libunwind
        pushd libunwind
        cp -r "$HONGGFUZZ_SRC"/third_party/android/libunwind/include .
        HOST_LIB_DIR=lib-${{matrix.HOST_ARCH}}
        mkdir $HOST_LIB_DIR
        cp "$HONGGFUZZ_SRC"/third_party/android/libunwind/src/.libs/*.a $HOST_LIB_DIR
        popd
        zip -r artifact.zip libunwind

    - name: Persist builds
      uses: actions/upload-artifact@v1
      with:
        name: libunwind_${{matrix.ANDROID_API}}_${{matrix.HOST_ARCH}}_${{matrix.TARGET_ARCH}}
        path: 'artifact.zip'
